"""
Proactive Anomaly & Insight Engine.

Runs a lightweight statistical check (Z-score) plus a couple of
domain-specific business rules over a query's result rows, and
returns a short list of flagged anomalies to surface as an alert
banner under the chart.

Column matching is done by KEYWORD, not exact name — the SQL
generated by the LLM often aliases aggregates (e.g. SUM(profit) AS
total_profit), so we match any column whose name *contains* the
keyword (case-insensitive) rather than requiring an exact "profit"
key. The matched column name is resolved once per result set (from
the first row) and reused for every row, since all rows share the
same columns.

Row labels only exclude the SPECIFIC column being reported for that
anomaly — not every metric-matched column — so a column like
"discount_rate" (which matches the "discount" keyword) can still be
used as the label when it's actually the grouping dimension, not the
value being flagged.
"""

import statistics
from decimal import Decimal
from typing import Optional

METRIC_KEYWORDS = ["profit", "sales", "discount", "quantity"]
NUMERIC_TYPES = (int, float, Decimal)
Z_SCORE_THRESHOLD = 2.5
MIN_ROWS_FOR_ZSCORE = 4
HIGH_DISCOUNT_THRESHOLD = 0.3
MAX_ANOMALIES_RETURNED = 5


def _is_numeric(value) -> bool:
    return isinstance(value, NUMERIC_TYPES) and not isinstance(value, bool)


def _match_column_name(sample_row: dict, keyword: str) -> Optional[str]:
    for key in sample_row.keys():
        if keyword in key.lower():
            return key
    return None


def _resolve_columns(results: list[dict]) -> dict:
    if not results:
        return {}
    sample_row = results[0]
    return {keyword: _match_column_name(sample_row, keyword) for keyword in METRIC_KEYWORDS}


def _row_label(row: dict, exclude_col: str) -> str:
    """
    Pick a human-readable label for a row, excluding only the specific
    column whose value is being reported (e.g. "profit"). Prefers a
    string column; falls back to formatting any other numeric column
    (e.g. "discount_rate: 0.30") rather than a generic "This row".
    """
    for key, value in row.items():
        if key != exclude_col and isinstance(value, str):
            return value

    for key, value in row.items():
        if key != exclude_col and _is_numeric(value):
            return f"{key}: {float(value):,.2f}"

    return "This row"


def _row_key(row: dict) -> tuple:
    return tuple(sorted(row.items()))


def _detect_negative_profit(results: list[dict], resolved_columns: dict, flagged: set) -> list[dict]:
    anomalies = []
    profit_col = resolved_columns.get("profit")
    if not profit_col:
        return anomalies

    for row in results:
        profit = row.get(profit_col)
        if _is_numeric(profit) and float(profit) < 0:
            key = (_row_key(row), profit_col)
            if key in flagged:
                continue
            flagged.add(key)
            anomalies.append({
                "type": "negative_profit",
                "column": profit_col,
                "message": f"{_row_label(row, profit_col)} is running at a loss ({float(profit):,.2f} profit).",
            })
    return anomalies


def _detect_profit_leak(results: list[dict], resolved_columns: dict, flagged: set) -> list[dict]:
    anomalies = []
    discount_col = resolved_columns.get("discount")
    profit_col = resolved_columns.get("profit")
    if not discount_col or not profit_col:
        return anomalies

    for row in results:
        discount = row.get(discount_col)
        profit = row.get(profit_col)
        if _is_numeric(discount) and _is_numeric(profit):
            discount_f, profit_f = float(discount), float(profit)
            if discount_f >= HIGH_DISCOUNT_THRESHOLD and profit_f <= 0:
                key = (_row_key(row), profit_col)
                if key in flagged:
                    continue
                flagged.add(key)
                anomalies.append({
                    "type": "profit_leak",
                    "column": profit_col,
                    "message": f"{_row_label(row, profit_col)} shows a possible profit leak: "
                               f"{discount_f:.0%} discount with {'a loss' if profit_f < 0 else 'zero profit'} "
                               f"({profit_f:,.2f}).",
                })
    return anomalies


def _detect_statistical_outliers(results: list[dict], resolved_columns: dict, flagged: set) -> list[dict]:
    anomalies = []
    if len(results) < MIN_ROWS_FOR_ZSCORE:
        return anomalies

    for keyword, column in resolved_columns.items():
        if not column:
            continue

        values = [float(row[column]) for row in results if _is_numeric(row.get(column))]
        if len(values) < MIN_ROWS_FOR_ZSCORE:
            continue

        mean = statistics.mean(values)
        try:
            stdev = statistics.stdev(values)
        except statistics.StatisticsError:
            continue
        if stdev == 0:
            continue

        for row in results:
            value = row.get(column)
            if not _is_numeric(value):
                continue
            value_f = float(value)
            z_score = (value_f - mean) / stdev
            if abs(z_score) >= Z_SCORE_THRESHOLD:
                key = (_row_key(row), column)
                if key in flagged:
                    continue
                flagged.add(key)
                direction = "unusually high" if z_score > 0 else "unusually low"
                anomalies.append({
                    "type": "statistical_outlier",
                    "column": column,
                    "message": f"{_row_label(row, column)} has {direction} {keyword} ({value_f:,.2f}, "
                               f"average is {mean:,.2f}).",
                })

    return anomalies


def detect_anomalies(results: Optional[list[dict]]) -> list[dict]:
    if not results:
        return []

    resolved_columns = _resolve_columns(results)
    flagged: set = set()
    anomalies = (
        _detect_negative_profit(results, resolved_columns, flagged)
        + _detect_profit_leak(results, resolved_columns, flagged)
        + _detect_statistical_outliers(results, resolved_columns, flagged)
    )
    return anomalies[:MAX_ANOMALIES_RETURNED]